// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    BaseHeader: typeof import("./src/components/BaseHeader/BaseHeader.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    VarButton: typeof import("@varlet/ui")["_ButtonComponent"];
    VarChip: typeof import("@varlet/ui")["_ChipComponent"];
  }
}

export {};
